application: my-blog
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /fonts
  static_dir: fonts
- url: /.*
  script: main.app

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]