application: my-1st-blog
version: 1
runtime: python27
api_version: 1
threadsafe: true
instance_class: F4_1G

handlers:
- url: /css
  static_dir: assets/css
- url: /js
  static_dir: assets/js
- url: /images
  static_dir: assets/images
- url: /fonts
  static_dir: assets/fonts
- url: /.*
  script: main.app

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
